name: Run hello.py and tests

on:
  push:
    branches:
      - main
      - 'feature-*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip

      - name: Run test.py
        run: |
          python test.py

  test-python:
    runs-on: ubuntu-latest
    needs: run-python-script   # optional: wait for the other job (remove if you want parallel)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest -q
